CREATE TABLE IF NOT EXISTS players (
  name TEXT PRIMARY KEY,
  score INTEGER NOT NULL,
  lives INTEGER NOT NULL,
  wave INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_score ON players(score DESC); 